<a href="https://colab.research.google.com/github/Harsh28-raj/dl_projects/blob/main/fnl_legal_case_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!mkdir -p ~/.kaggle

!cp kaggle.json ~/.kaggle/

!chmod 600 ~/.kaggle/kaggle.json

In [2]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (1.7.4.5)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2026.2.25)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.4.5)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.11)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.5.1)

In [3]:
!kaggle datasets download -d vangap/indian-supreme-court-judgments

Dataset URL: https://www.kaggle.com/datasets/vangap/indian-supreme-court-judgments
License(s): CC-BY-NC-SA-4.0
Downloading indian-supreme-court-judgments.zip to /content
100% 4.75G/4.77G [01:10<00:00, 270MB/s]
100% 4.77G/4.77G [01:10<00:00, 73.1MB/s]

In [4]:
!unzip indian-supreme-court-judgments.zip judgments.csv

Archive:  indian-supreme-court-judgments.zip
  inflating: judgments.csv

In [5]:
import pandas as pd

df=pd.read_csv("judgments.csv")

df.head()

,diary_no,Judgement_type,case_no,pet,res,pet_adv,res_adv,bench,judgement_by,judgment_dates,temp_link,language
0,5-2021,J,MA-000083 - 2021,UNION OF INDIA,ASSOCIATION OF UNIFIED TELECOM SERVICEPROVIDER...,B. VIJAYALAKSHMI MENON,NaN,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,23-07-2021,supremecourt/2021/5/5_2021_36_1501_28814_Judge...,NaN
1,28-2021,J,C.A. No.-000867-000867 - 2021,INDEX MEDICAL COLLEGE HOSPITAL AND RESEARCH CE...,THE STATE OF MADHYA PRADESH,NISHIT AGRAWAL,NaN,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,03-02-2021,supremecourt/2021/28/28_2021_38_14_25922_Judge...,NaN
2,70-2020,J,Crl.A. No.-000167-000167 - 2021,ARCHANA RANA,THE STATE OF UTTAR PRADESH,SANJEEV MALHOTRA,NaN,"HON'BLE THE CHIEF JUSTICE, HON'BLE MR. JUSTICE...",HON'BLE THE CHIEF JUSTICE,01-03-2021,supremecourt/2020/70/70_2020_36_1503_26554_Jud...,NaN
3,82-2021,J,SLP(C) No.-000811 - 2021,THE EMPLOYEES STATE INSURANCE CORPORATION,M/S. TEXMO INDUSTRIES,MRIDULA RAY BHARADWAJ,NaN,"HON'BLE MS. JUSTICE INDIRA BANERJEE, HON'BLE M...",HON'BLE MS. JUSTICE INDIRA BANERJEE,08-03-2021,supremecourt/2021/82/82_2021_43_13_26745_Judge...,NaN
4,114-2021,J,C.A. No.-000390-000390 - 2021,KALOJI NARAYANA RAO UNIVERSITY OF HEALTH SCIENCES,SRIKEERTI REDDI PINGLE,VENKAT PALWAI LAW ASSOCIATES,NaN,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE S. RAVINDRA BHAT,16-02-2021,supremecourt/2021/114/114_2021_38_1501_26229_J...,NaN

In [6]:
!rm indian-supreme-court-judgments.zip

In [65]:
df.sample(1000)

,case_no,pet_adv,bench,judgement_by,judgment_dates,case_type,lawyer_exp,judge_exp,judge_count,complexity,evidence,win_score,outcome
22242,C.A. No.-014630-014630 - 2015,S. MAHENDRAN,"HON'BLE MR. JUSTICE C.T. RAVIKUMAR, HON'BLE MR...",HON'BLE MR. JUSTICE C.T. RAVIKUMAR,20-09-2023,1,0.077778,0.022912,3,23,0.874241,0.292012,0
24663,C.A. No.-007027-007028 - 2009,ARVIND KUMAR SHARMA,"HON'BLE MR. JUSTICE R. SUBHASH REDDY, HON'BLE ...",HON'BLE MR. JUSTICE HRISHIKESH ROY,03-01-2022,1,0.800000,0.036216,3,11,0.534848,0.539653,1
1345,Crl.A. No.-001889-001889 - 2010,SUSHIL BALWADA,"HON'BLE MR. JUSTICE MOHAN M. SHANTANAGOUDAR, H...",HON'BLE MR. JUSTICE MOHAN M. SHANTANAGOUDAR,24-10-2019,0,0.244444,0.087953,3,19,0.435985,0.292179,1
2068,ARBIT.PETITON No.-000065-000065 - 2016,ASHWANI KUMAR,"HON'BLE MR. JUSTICE A.M. KHANWILKAR, HON'BLE M...",HON'BLE MR. JUSTICE A.M. KHANWILKAR,01-07-2019,4,0.177778,0.133038,3,25,0.437151,0.260675,1
24917,C.A. No.-002859-002861 - 2022,PRAVEEN AGRAWAL,"HON'BLE MR. JUSTICE DINESH MAHESHWARI, HON'BLE...",HON'BLE MR. JUSTICE DINESH MAHESHWARI,30-03-2022,1,0.077778,0.101256,3,12,0.757169,0.371811,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8393,C.A. No.-019662-019662 - 2017,GAURAV SHARMA,"HON'BLE THE CHIEF JUSTICE, HON'BLE MR. JUSTICE...",HON'BLE THE CHIEF JUSTICE,23-11-2017,1,0.233333,1.000000,4,23,0.656629,0.588282,1
114,C.A. No.-007017-007017 - 2009,KAMLENDRA MISHRA,"HON'BLE MR. JUSTICE HEMANT GUPTA, HON'BLE MR. ...",HON'BLE MR. JUSTICE HEMANT GUPTA,05-10-2021,1,0.200000,0.122690,3,18,0.894210,0.386760,0
22515,C.A. No.-003992-004000 - 2011,PRAGATI NEEKHRA,"HON'BLE MS. JUSTICE BELA M. TRIVEDI, HON'BLE M...",HON'BLE MS. JUSTICE BELA M. TRIVEDI,17-08-2023,1,0.122222,0.026608,3,23,0.748824,0.281370,0
52,C.A. No.-000843-000844 - 2021,PRADEEP KUMAR MATHUR,"HON'BLE MS. JUSTICE INDU MALHOTRA, HON'BLE MR....",HON'BLE MS. JUSTICE INDU MALHOTRA,10-03-2021,1,0.077778,0.048041,3,13,0.729155,0.337423,0
1357,Crl.A. No.-000296-000296 - 2014,SHIV KUMAR SURI,"HON'BLE MR. JUSTICE DEEPAK GUPTA, HON'BLE MR. ...",HON'BLE MR. JUSTICE DEEPAK GUPTA,04-09-2019,0,0.188889,0.090909,3,18,0.845413,0.364133,0

In [66]:
df.shape

(8094, 13)

In [67]:
df.columns

Index(['case_no', 'pet_adv', 'bench', 'judgement_by', 'judgment_dates',
       'case_type', 'lawyer_exp', 'judge_exp', 'judge_count', 'complexity',
       'evidence', 'win_score', 'outcome'],
      dtype='object')

In [68]:
df=df.drop([
'diary_no',
'Judgement_type',
'pet',
'res',
'res_adv',
'temp_link',
'language'
],axis=1)

KeyError: "['diary_no', 'Judgement_type', 'pet', 'res', 'res_adv', 'temp_link', 'language'] not found in axis"

In [69]:
df.head()

,case_no,pet_adv,bench,judgement_by,judgment_dates,case_type,lawyer_exp,judge_exp,judge_count,complexity,evidence,win_score,outcome
0,MA-000083 - 2021,B. VIJAYALAKSHMI MENON,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,23-07-2021,4,0.166667,0.184035,4,15,0.876680,0.413880,0
1,C.A. No.-000867-000867 - 2021,NISHIT AGRAWAL,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,03-02-2021,1,0.077778,0.184035,3,19,0.547668,0.293341,0
2,Crl.A. No.-000167-000167 - 2021,SANJEEV MALHOTRA,"HON'BLE THE CHIEF JUSTICE, HON'BLE MR. JUSTICE...",HON'BLE THE CHIEF JUSTICE,01-03-2021,0,0.077778,1.000000,3,16,0.569536,0.562241,1
3,SLP(C) No.-000811 - 2021,MRIDULA RAY BHARADWAJ,"HON'BLE MS. JUSTICE INDIRA BANERJEE, HON'BLE M...",HON'BLE MS. JUSTICE INDIRA BANERJEE,08-03-2021,2,0.077778,0.092387,3,15,0.528168,0.290016,0
4,C.A. No.-000390-000390 - 2021,VENKAT PALWAI LAW ASSOCIATES,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE S. RAVINDRA BHAT,16-02-2021,1,0.100000,0.082779,3,15,0.784486,0.345064,0

In [70]:
df.dropna()

,case_no,pet_adv,bench,judgement_by,judgment_dates,case_type,lawyer_exp,judge_exp,judge_count,complexity,evidence,win_score,outcome
0,MA-000083 - 2021,B. VIJAYALAKSHMI MENON,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,23-07-2021,4,0.166667,0.184035,4,15,0.876680,0.413880,0
1,C.A. No.-000867-000867 - 2021,NISHIT AGRAWAL,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,03-02-2021,1,0.077778,0.184035,3,19,0.547668,0.293341,0
2,Crl.A. No.-000167-000167 - 2021,SANJEEV MALHOTRA,"HON'BLE THE CHIEF JUSTICE, HON'BLE MR. JUSTICE...",HON'BLE THE CHIEF JUSTICE,01-03-2021,0,0.077778,1.000000,3,16,0.569536,0.562241,1
3,SLP(C) No.-000811 - 2021,MRIDULA RAY BHARADWAJ,"HON'BLE MS. JUSTICE INDIRA BANERJEE, HON'BLE M...",HON'BLE MS. JUSTICE INDIRA BANERJEE,08-03-2021,2,0.077778,0.092387,3,15,0.528168,0.290016,0
4,C.A. No.-000390-000390 - 2021,VENKAT PALWAI LAW ASSOCIATES,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE S. RAVINDRA BHAT,16-02-2021,1,0.100000,0.082779,3,15,0.784486,0.345064,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
47105,C.A. No.-004715-004715 - 2011,SANJAY KAPUR,"HON'BLE MR. JUSTICE T.S. THAKUR, HON'BLE MR. J...",HON'BLE MR. JUSTICE A.M. KHANWILKAR,16-09-2016,1,0.355556,0.133038,3,19,0.676909,0.387223,0
47106,C.A. No.-004715-004715 - 2011,SANJAY KAPUR,"HON'BLE MR. JUSTICE T.S. THAKUR, HON'BLE MR. J...",HON'BLE MR. JUSTICE A.M. KHANWILKAR,16-09-2016,1,0.355556,0.133038,3,17,0.428014,0.349828,0
47169,C.A. No.-010860-010860 - 2016,CYRIL AMARCHAND MANGALDAS AOR,"HON'BLE MR. JUSTICE KURIAN JOSEPH, HON'BLE MR....",HON'BLE MR. JUSTICE ROHINTON FALI NARIMAN,15-11-2016,1,0.111111,0.164080,3,16,0.569019,0.321361,1
47170,C.A. No.-010860-010860 - 2016,CYRIL AMARCHAND MANGALDAS AOR,"HON'BLE MR. JUSTICE KURIAN JOSEPH, HON'BLE MR....",HON'BLE MR. JUSTICE ROHINTON FALI NARIMAN,15-11-2016,1,0.111111,0.164080,3,25,0.613427,0.285243,1
47236,C.A. No.-010951-010951 - 2016,SHARMILA UPADHYAY,"HON'BLE MR. JUSTICE A.K. SIKRI, HON'BLE MRS. J...",HON'BLE MR. JUSTICE A.K. SIKRI,14-12-2016,1,0.111111,0.116038,3,18,0.717674,0.322791,1

In [71]:
df.shape

(8094, 13)

In [72]:
df.head()

,case_no,pet_adv,bench,judgement_by,judgment_dates,case_type,lawyer_exp,judge_exp,judge_count,complexity,evidence,win_score,outcome
0,MA-000083 - 2021,B. VIJAYALAKSHMI MENON,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,23-07-2021,4,0.166667,0.184035,4,15,0.876680,0.413880,0
1,C.A. No.-000867-000867 - 2021,NISHIT AGRAWAL,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,03-02-2021,1,0.077778,0.184035,3,19,0.547668,0.293341,0
2,Crl.A. No.-000167-000167 - 2021,SANJEEV MALHOTRA,"HON'BLE THE CHIEF JUSTICE, HON'BLE MR. JUSTICE...",HON'BLE THE CHIEF JUSTICE,01-03-2021,0,0.077778,1.000000,3,16,0.569536,0.562241,1
3,SLP(C) No.-000811 - 2021,MRIDULA RAY BHARADWAJ,"HON'BLE MS. JUSTICE INDIRA BANERJEE, HON'BLE M...",HON'BLE MS. JUSTICE INDIRA BANERJEE,08-03-2021,2,0.077778,0.092387,3,15,0.528168,0.290016,0
4,C.A. No.-000390-000390 - 2021,VENKAT PALWAI LAW ASSOCIATES,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE S. RAVINDRA BHAT,16-02-2021,1,0.100000,0.082779,3,15,0.784486,0.345064,0

In [73]:
df.head()

,case_no,pet_adv,bench,judgement_by,judgment_dates,case_type,lawyer_exp,judge_exp,judge_count,complexity,evidence,win_score,outcome
0,MA-000083 - 2021,B. VIJAYALAKSHMI MENON,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,23-07-2021,4,0.166667,0.184035,4,15,0.876680,0.413880,0
1,C.A. No.-000867-000867 - 2021,NISHIT AGRAWAL,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,03-02-2021,1,0.077778,0.184035,3,19,0.547668,0.293341,0
2,Crl.A. No.-000167-000167 - 2021,SANJEEV MALHOTRA,"HON'BLE THE CHIEF JUSTICE, HON'BLE MR. JUSTICE...",HON'BLE THE CHIEF JUSTICE,01-03-2021,0,0.077778,1.000000,3,16,0.569536,0.562241,1
3,SLP(C) No.-000811 - 2021,MRIDULA RAY BHARADWAJ,"HON'BLE MS. JUSTICE INDIRA BANERJEE, HON'BLE M...",HON'BLE MS. JUSTICE INDIRA BANERJEE,08-03-2021,2,0.077778,0.092387,3,15,0.528168,0.290016,0
4,C.A. No.-000390-000390 - 2021,VENKAT PALWAI LAW ASSOCIATES,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE S. RAVINDRA BHAT,16-02-2021,1,0.100000,0.082779,3,15,0.784486,0.345064,0

In [74]:
lawyer_counts=df['pet_adv'].value_counts()

In [75]:
lawyer_counts

pet_adv
PETITIONER-IN-PERSON    90
ANIL KATIYAR            90
MUKESH KUMAR MARORIA    80
E. C. AGRAWALA          77
B. KRISHNA PRASAD       74
                        ..
SAROJ TRIPATHI           1
SRIDEVI PANIKKAR         1
GAURAV DHINGRA           1
ACM LEGAL                1
LEMAX LAWYERS & CO.      1
Name: count, Length: 1370, dtype: int64

In [76]:
import numpy as np

In [77]:
df=df.dropna()

In [78]:
print(df.columns)

Index(['case_no', 'pet_adv', 'bench', 'judgement_by', 'judgment_dates',
       'case_type', 'lawyer_exp', 'judge_exp', 'judge_count', 'complexity',
       'evidence', 'win_score', 'outcome'],
      dtype='object')

In [79]:
def get_case_type(x):

    x=str(x)

    if "Crl" in x:
        return 0
    elif "C.A" in x:
        return 1
    elif "SLP" in x:
        return 2
    elif "W.P" in x:
        return 3
    else:
        return 4

df['case_type']=df['case_no'].apply(get_case_type)

In [80]:
lawyer_counts=df['pet_adv'].value_counts()

df['lawyer_exp']=df['pet_adv'].map(lawyer_counts)

df['lawyer_exp']=df['lawyer_exp']/df['lawyer_exp'].max()

In [81]:
judge_counts=df['judgement_by'].value_counts()

df['judge_exp']=df['judgement_by'].map(judge_counts)

df['judge_exp']=df['judge_exp']/df['judge_exp'].max()

In [82]:
df['judge_count']=df['bench'].str.count("JUSTICE")+1

In [83]:
df['complexity'] = df['judge_count']*2 + np.random.randint(5,20,len(df))

df['evidence']=np.random.uniform(0.4,0.9,len(df))

df['win_score']=(
0.30*df['lawyer_exp']+
0.30*df['judge_exp']+
0.20*df['evidence']+
0.20*(1/(df['complexity']/10))
)

df['win_score']=df['win_score'].clip(0.05,0.95)

df['outcome']=np.random.binomial(1,df['win_score'])

In [84]:
FEATURES=[
'case_type',
'lawyer_exp',
'judge_exp',
'judge_count',
'complexity',
'evidence'
]

X=df[FEATURES]

y=df['outcome']

In [85]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(
X,
y,
test_size=0.2,
stratify=y,
random_state=42
)

In [86]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

X_train=scaler.fit_transform(X_train)

X_test=scaler.transform(X_test)

In [87]:
from sklearn.linear_model import LogisticRegression

log_model=LogisticRegression(
max_iter=2000,
C=0.3,
class_weight='balanced',
random_state=42
)
log_model.fit(X_train,y_train)

LogisticRegression(C=0.3, class_weight='balanced', max_iter=2000,
                   random_state=42)

In [88]:
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier(
n_estimators=300,
max_depth=10,
random_state=42
)

rf.fit(X_train,y_train)

RandomForestClassifier(max_depth=10, n_estimators=300, random_state=42)

In [89]:
from xgboost import XGBClassifier

xgb=XGBClassifier(
n_estimators=300,
learning_rate=0.05,
max_depth=6,
random_state=42
)

xgb.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, ...)

In [90]:
from sklearn.metrics import accuracy_score

log_pred=log_model.predict(X_test)

rf_pred=rf.predict(X_test)

xgb_pred=xgb.predict(X_test)

print("Logistic:",accuracy_score(y_test,log_pred))

print("RF:",accuracy_score(y_test,rf_pred))

print("XGB:",accuracy_score(y_test,xgb_pred))

Logistic: 0.6429894996911674
RF: 0.6429894996911674
XGB: 0.6176652254478073

In [91]:
prob=log_model.predict_proba(X_test)

print(prob[:5])

[[0.12822167 0.87177833]
 [0.32340428 0.67659572]
 [0.24990487 0.75009513]
 [0.33923673 0.66076327]
 [0.55758992 0.44241008]]

In [92]:
def predict_case(case_type,lawyer_exp,judge_exp,judge_count,complexity,evidence):

    sample=pd.DataFrame(
        [[case_type,lawyer_exp,judge_exp,judge_count,complexity,evidence]],
        columns=FEATURES
    )

    sample=scaler.transform(sample)

    prob=log_model.predict_proba(sample)

    win=float(prob[0][1]*100)

    if win>70:
        strength="Strong"

    elif win>50:
        strength="Moderate"

    else:
        strength="Weak"

    return {
        "Win probability":round(win,2),
        "Case strength":strength
    }

In [93]:
predict_case(1,0.3,0.5,3,18,0.7)

{'Win probability': 59.18, 'Case strength': 'Moderate'}

In [94]:
log_model.fit(X_train,y_train)
rf.fit(X_train,y_train)
xgb.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, ...)

In [95]:
from sklearn.metrics import accuracy_score,classification_report,f1_score

models={
    "Logistic Regression":log_model,
    "Random Forest":rf,
    "XGBoost":xgb
}

for name,model in models.items():

    pred=model.predict(X_test)

    acc=accuracy_score(y_test,pred)

    f1=f1_score(y_test,pred)

    print("======",name,"======")

    print("Accuracy:",round(acc*100,2),"%")

    print("F1 Score:",round(f1*100,2),"%")

    print(classification_report(y_test,pred))

    print()

====== Logistic Regression ======
Accuracy: 64.3 %
F1 Score: 54.49 %
              precision    recall  f1-score   support

           0       0.69      0.72      0.71       967
           1       0.56      0.53      0.54       652

    accuracy                           0.64      1619
   macro avg       0.63      0.62      0.63      1619
weighted avg       0.64      0.64      0.64      1619


====== Random Forest ======
Accuracy: 64.3 %
F1 Score: 42.89 %
              precision    recall  f1-score   support

           0       0.65      0.85      0.74       967
           1       0.60      0.33      0.43       652

    accuracy                           0.64      1619
   macro avg       0.63      0.59      0.58      1619
weighted avg       0.63      0.64      0.61      1619


====== XGBoost ======
Accuracy: 61.77 %
F1 Score: 42.53 %
              precision    recall  f1-score   support

           0       0.65      0.80      0.71       967
           1       0.54      0.35      0.43       652

    accuracy                           0.62      1619
   macro avg       0.59      0.57      0.57      1619
weighted avg       0.60      0.62      0.60      1619

In [96]:
results=[]

for name,model in models.items():

    pred=model.predict(X_test)

    acc=accuracy_score(y_test,pred)

    f1=f1_score(y_test,pred)

    results.append([name,acc,f1])

results_df=pd.DataFrame(
results,
columns=["Model","Accuracy","F1 Score"]
)

results_df

                 Model  Accuracy  F1 Score
0  Logistic Regression  0.642989  0.544882
1        Random Forest  0.642989  0.428854
2              XGBoost  0.617665  0.425255

In [97]:
from sklearn.metrics import roc_auc_score

for name,model in models.items():

    prob=model.predict_proba(X_test)[:,1]

    auc=roc_auc_score(y_test,prob)

    print(name,"ROC AUC:",round(auc,3))

Logistic Regression ROC AUC: 0.666
Random Forest ROC AUC: 0.649
XGBoost ROC AUC: 0.623

In [98]:
predict_case(1,0,0,0,18,0.7)

{'Win probability': 29.29, 'Case strength': 'Weak'}

In [101]:
predict_case(0,0,4,0,0,0)

{'Win probability': 98.3, 'Case strength': 'Strong'}